### ISSUE TITLE
OOMScoreAdj is incorrectly cleared even if no plugin performs an adjustment

### ISSUE THREAD

**Issue by samuelkarp** [containerd/nri#117]
From https://github.com/kubernetes/kubernetes/issues/128251, and see the new failing unit test in https://github.com/containerd/nri/pull/116.

**Comment by mikebrow** [comment]
@klihub FYI

**Comment by samuelkarp** [comment]
Leaving this open to track the remainder of the work:

- [ ] new tag for `github.com/containerd/nri`
- [ ] update containerd to consume the new version
