### ISSUE TITLE
nri depends on 4 years old runc as a transitive dependency

### ISSUE THREAD

**Issue by mathetake** [containerd/nri#14]
Ref: https://github.com/containerd/nri/blob/main/go.sum#L430

We found this out by adding google/go-containerregistry(https://github.com/google/go-containerregistry) in Istio project, and after digging into the dependency tree a bit, I realized that containerd/nri is the root cause of this fairly old transitive dependency. https://github.com/istio/istio/pull/33812#issuecomment-876823641

**Comment by fuweid** [comment]
NRI uses runc@v1.0.0-rc93 right now. 

https://github.com/containerd/nri/blob/main/go.sum#L434.

Closing.
