### ISSUE TITLE
Need more details on config paths and formats for hook-injector

### ISSUE THREAD

**Issue by swgriffith** [containerd/nri#33]
I've been able to get the hook injector working on a cluster with containerd 1.7-rc3, both by running the hook-injector directly and by dropping it in the /opt/nri/plugins directory, however I'm having issues working out where the hook-injector config files should be placed. I'm following the details shared here: 

https://github.com/containerd/nri/tree/main/plugins/hook-injector

I'll keep testing, but any guidance would be apprciated.

**Comment by swgriffith** [comment]
I worked it out, and I'm happy to PR some added details, unless there's a larger documentation refresh already in progress.

**Comment by klihub** [comment]
I assume that by 'hook injector config files' you refer to the actual hook schema files et. al, which the hook manager uses to decide whether and how to inject any hooks into a container ? If you have fixes for the docs then any PR is welcome.

Could you also include a fix for the outdated/broken hook manager link while at it ? I just noticed when trying to follow the link above through the injector to the hook manager that it has apparently been split out ages ago to `https://github.com/containers/common/tree/main/pkg/hooks`. Our link neither points to the exact version we use (commit 8bcc086b1b9d) nor to an up-to-date split out version. We should point our link to the exact sha1 version we use.

**Comment by mikebrow** [comment]
Please reopen if you believe more should be documented here.  Thx!
